### ISSUE TITLE
manifest.js file missing

### ISSUE THREAD

**Issue by nagtegaal** [alex3305/lovelace-global-mod#1]
When trying to add `https://github.com/alex3305/lovelace-global-mod` to HACS (2.0), it complains that the manifest.js file is missing.
Installing through HACS ain't possible....

**Comment by alex3305** [comment]
Hi 👋,

Thank you for pointing this out. Global Mod is a Lovelace plugin, not an integration. You should choose Lovelace as a category to add Global Mod to your installation

![image](https://github.com/user-attachments/assets/ddf61463-9b5a-46c9-9dd5-e9684e2f71be)

I will clarify this in the README.

**Comment by ThomDietrich** [comment]
Hey @alex3305, I know it's stupid but I just ran into the exact same problem :D

Thanks for your work!
